//! Generate the kitest harness source from a resolved fixture graph.
//!
//! Shape (validated by hand first): one tokio runtime; `SimpleRunner`
//! (single-threaded, in order); tests grouped by leaf module; a group runner
//! that builds the group's ancestor (borrowed) fixtures into a per-group
//! thread-local context; each test closure pulls borrowed fixtures from that
//! context, builds its owned per-test fixtures fresh, and runs the async body
//! via `Handle::block_on`.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write;

use anyhow::{Result, bail};
use rustdoc_ir::Type;

use crate::discover::{Discovery, MarkerKind};
use crate::graph::{Graph, Ownership};

/// Render a `rustdoc_ir::Type` as Rust source. Paths already carry the crate
/// name as their first segment, so they're valid from the harness target.
fn render_type(ty: &Type) -> Result<String> {
    match ty {
        Type::Path(p) => {
            if !p.generic_arguments.is_empty() {
                bail!("generic types in fixture/test signatures are not supported yet");
            }
            Ok(p.base_type.join("::"))
        }
        Type::Reference(r) => Ok(format!(
            "{}{}",
            if r.is_mutable { "&mut " } else { "&" },
            render_type(&r.inner)?
        )),
        other => bail!("unsupported type in a fixture/test signature: {other:?}"),
    }
}

/// `crate::path::to::name` for a discovered item, from the harness target's view.
fn item_path(discovery: &Discovery, idx: usize) -> String {
    let item = &discovery.items[idx];
    let mut segments = vec![discovery.crate_name.clone()];
    segments.extend(item.module_path.iter().cloned());
    segments.push(item.name.clone());
    segments.join("::")
}

/// Group key for a module path (the `extra` metadata + run_group match arm).
fn group_key(module_path: &[String]) -> String {
    if module_path.is_empty() {
        "crate".to_string()
    } else {
        module_path.join("::")
    }
}

/// A camel-case identifier for a group, used to name its fixtures struct and
/// thread-local.
fn group_ident(module_path: &[String]) -> String {
    if module_path.is_empty() {
        return "Crate".to_string();
    }
    module_path
        .iter()
        .map(|seg| {
            let mut chars = seg.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect::<String>(),
                None => String::new(),
            }
        })
        .collect()
}

/// Call expression for invoking a fixture/test, wrapping async ones in
/// `<handle>.block_on(...)`.
fn call_expr(discovery: &Discovery, idx: usize, args: &[String], handle: &str) -> String {
    let path = item_path(discovery, idx);
    let call = format!("{path}({})", args.join(", "));
    if discovery.items[idx].sig.is_async {
        format!("{handle}.block_on({call})")
    } else {
        call
    }
}

pub fn generate(discovery: &Discovery, graph: &Graph) -> Result<String> {
    if !graph.errors.is_empty() {
        bail!("cannot generate a harness: the fixture graph has unresolved errors");
    }

    // node index == item index (graph builds nodes in item order).
    let node_of = |i: usize| &graph.nodes[i];

    // A fixture is "shared" (lives in a group's context) if anything borrows it.
    let mut shared: HashSet<usize> = HashSet::new();
    for node in &graph.nodes {
        for edge in &node.edges {
            if edge.ownership == Ownership::Borrowed {
                shared.insert(edge.target);
            }
        }
    }

    // Group tests by their module path.
    let mut groups: BTreeMap<Vec<String>, Vec<usize>> = BTreeMap::new();
    for (i, item) in discovery.items.iter().enumerate() {
        if item.kind == MarkerKind::Test {
            groups.entry(item.module_path.clone()).or_default().push(i);
        }
    }

    let mut out = String::new();
    writeln!(out, "// @generated by testrs — do not edit.")?;
    writeln!(out, "#![allow(unknown_or_malformed_diagnostic_attributes)]")?;
    writeln!(out)?;
    writeln!(out, "use std::cell::RefCell;")?;
    writeln!(out, "use std::ops::ControlFlow;")?;
    writeln!(out, "use std::process::Termination;")?;
    writeln!(out)?;
    writeln!(out, "use kitest::group::{{TestGroupOutcomes, TestGroupRunner}};")?;
    writeln!(out, "use kitest::prelude::*;")?;
    writeln!(out, "use kitest::runner::SimpleRunner;")?;
    writeln!(out, "use tokio::runtime::Handle;")?;
    writeln!(out)?;

    // Per-group context struct + thread-local holding that group's shared fixtures.
    let mut group_meta = Vec::new(); // (module_path, ident, key, shared fixtures in setup order)
    for module_path in groups.keys() {
        let ident = group_ident(module_path);
        let key = group_key(module_path);

        // Shared fixtures reachable (transitively) from this group's tests.
        let reachable = reachable_fixtures(graph, &groups[module_path]);
        let ctx_fixtures: Vec<usize> = graph
            .fixture_order
            .iter()
            .copied()
            .filter(|i| shared.contains(i) && reachable.contains(i))
            .collect();

        writeln!(out, "#[derive(Default)]")?;
        writeln!(out, "struct {ident}Fixtures {{")?;
        for &fi in &ctx_fixtures {
            let field = &discovery.items[fi].name;
            let ty = render_type(discovery.items[fi].sig.output.as_ref().unwrap())?;
            writeln!(out, "    {field}: Option<{ty}>,")?;
        }
        writeln!(out, "}}")?;
        writeln!(out, "thread_local! {{")?;
        writeln!(
            out,
            "    static {}: RefCell<{ident}Fixtures> = RefCell::new({ident}Fixtures::default());",
            ident.to_uppercase()
        )?;
        writeln!(out, "}}")?;
        writeln!(out)?;

        group_meta.push((module_path.clone(), ident, key, ctx_fixtures));
    }

    // Group runner: set up each group's shared fixtures, run, tear down.
    writeln!(out, "struct FixtureRunner {{ handle: Handle }}")?;
    writeln!(out)?;
    writeln!(
        out,
        "impl<'t> TestGroupRunner<'t, &'static str, &'static str, ()> for FixtureRunner {{"
    )?;
    writeln!(
        out,
        "    fn run_group<F>(&self, f: F, key: &&'static str, _ctx: Option<&()>)"
    )?;
    writeln!(
        out,
        "        -> ControlFlow<TestGroupOutcomes<'t>, TestGroupOutcomes<'t>>"
    )?;
    writeln!(out, "    where F: FnOnce() -> TestGroupOutcomes<'t> {{")?;
    writeln!(out, "        match *key {{")?;
    for (_module_path, ident, key, ctx_fixtures) in &group_meta {
        let tl = ident.to_uppercase();
        writeln!(out, "            {key:?} => {{")?;
        // Build shared fixtures as locals in topo order.
        for &fi in ctx_fixtures {
            let local = &discovery.items[fi].name;
            let args = call_args(discovery, node_of(fi), CtxAccess::Local, "self.handle")?;
            let expr = call_expr(discovery, fi, &args, "self.handle");
            writeln!(out, "                let {local} = {expr};")?;
        }
        writeln!(out, "                {tl}.with(|c| {{")?;
        writeln!(out, "                    let mut c = c.borrow_mut();")?;
        for &fi in ctx_fixtures {
            let field = &discovery.items[fi].name;
            writeln!(out, "                    c.{field} = Some({field});")?;
        }
        writeln!(out, "                }});")?;
        writeln!(out, "                let outcomes = f();")?;
        writeln!(out, "                {tl}.with(|c| *c.borrow_mut() = {ident}Fixtures::default());")?;
        writeln!(out, "                ControlFlow::Continue(outcomes)")?;
        writeln!(out, "            }}")?;
    }
    writeln!(out, "            _ => ControlFlow::Continue(f()),")?;
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // The test list.
    writeln!(out, "fn tests(handle: Handle) -> Vec<Test<&'static str>> {{")?;
    writeln!(out, "    vec![")?;
    for (module_path, ident, key, _ctx) in &group_meta {
        let tl = ident.to_uppercase();
        for &ti in &groups[module_path] {
            let name = &discovery.items[ti].name;
            writeln!(out, "        Test::new(")?;
            writeln!(out, "            TestFnHandle::from_boxed({{")?;
            writeln!(out, "                let handle = handle.clone();")?;
            writeln!(out, "                move || {{")?;
            writeln!(out, "                    {tl}.with(|c| {{")?;
            writeln!(out, "                        let c = c.borrow();")?;
            // Build the test's owned per-test fixtures, then call the body.
            let (owned_stmts, owned_locals) = emit_owned(discovery, graph, ti, "handle")?;
            for stmt in &owned_stmts {
                writeln!(out, "                        {stmt}")?;
            }
            let args = call_args_with(discovery, node_of(ti), &owned_locals, "handle")?;
            writeln!(out, "                        {};", call_expr(discovery, ti, &args, "handle"))?;
            writeln!(out, "                    }});")?;
            writeln!(out, "                }}")?;
            writeln!(out, "            }}),")?;
            writeln!(
                out,
                "            TestMeta {{ name: {name:?}.into(), extra: {key:?}, ..Default::default() }},"
            )?;
            writeln!(out, "        ),")?;
        }
    }
    writeln!(out, "    ]")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // main.
    writeln!(out, "fn main() -> impl Termination {{")?;
    writeln!(out, "    let rt = tokio::runtime::Runtime::new().unwrap();")?;
    writeln!(out, "    let handle = rt.handle().clone();")?;
    writeln!(out, "    let tests = tests(handle.clone());")?;
    writeln!(out, "    kitest::harness(&tests)")?;
    writeln!(out, "        .with_grouper(|m: &TestMeta<&'static str>| m.extra)")?;
    writeln!(out, "        .with_group_runner(FixtureRunner {{ handle }})")?;
    writeln!(out, "        .with_runner(SimpleRunner::default())")?;
    writeln!(out, "        .run()")?;
    writeln!(out, "        .report()")?;
    writeln!(out, "}}")?;

    Ok(out)
}

/// How a borrowed dependency is accessed when building a fixture call.
enum CtxAccess {
    /// Inside `run_group`, building shared fixtures as locals: `&<name>`.
    Local,
}

/// Build the argument list for a node whose borrowed deps come from locals
/// (used inside `run_group`).
fn call_args(
    discovery: &Discovery,
    node: &crate::graph::Node,
    access: CtxAccess,
    _handle: &str,
) -> Result<Vec<String>> {
    let CtxAccess::Local = access;
    let mut args = Vec::new();
    for edge in &node.edges {
        match edge.ownership {
            Ownership::Borrowed => args.push(format!("&{}", discovery.items[edge.target].name)),
            Ownership::Owned => {
                bail!("owned dependency of a shared fixture is not supported yet")
            }
        }
    }
    Ok(args)
}

/// Build the argument list for a node inside a test closure: borrowed deps come
/// from the group context (`c.<field>`), owned deps from previously-built locals.
fn call_args_with(
    discovery: &Discovery,
    node: &crate::graph::Node,
    owned_locals: &std::collections::HashMap<usize, String>,
    _handle: &str,
) -> Result<Vec<String>> {
    let mut args = Vec::new();
    for edge in &node.edges {
        match edge.ownership {
            Ownership::Borrowed => args.push(format!(
                "c.{}.as_ref().unwrap()",
                discovery.items[edge.target].name
            )),
            Ownership::Owned => args.push(owned_locals[&edge.target].clone()),
        }
    }
    Ok(args)
}

/// Emit statements building all owned per-test fixtures required (transitively)
/// by `consumer`, in dependency order. Returns the statements and a map from
/// fixture index to its local variable name.
fn emit_owned(
    discovery: &Discovery,
    graph: &Graph,
    consumer: usize,
    handle: &str,
) -> Result<(Vec<String>, std::collections::HashMap<usize, String>)> {
    let mut stmts = Vec::new();
    let mut locals = std::collections::HashMap::new();
    let mut building = HashSet::new();
    build_owned(discovery, graph, consumer, handle, &mut stmts, &mut locals, &mut building)?;
    Ok((stmts, locals))
}

fn build_owned(
    discovery: &Discovery,
    graph: &Graph,
    consumer: usize,
    handle: &str,
    stmts: &mut Vec<String>,
    locals: &mut std::collections::HashMap<usize, String>,
    building: &mut HashSet<usize>,
) -> Result<()> {
    for edge in &graph.nodes[consumer].edges {
        if edge.ownership != Ownership::Owned {
            continue;
        }
        let target = edge.target;
        if locals.contains_key(&target) || building.contains(&target) {
            continue;
        }
        building.insert(target);
        // Build this owned fixture's own owned deps first.
        build_owned(discovery, graph, target, handle, stmts, locals, building)?;
        let args = call_args_with(discovery, &graph.nodes[target], locals, handle)?;
        let local = discovery.items[target].name.clone();
        stmts.push(format!("let {local} = {};", call_expr(discovery, target, &args, handle)));
        locals.insert(target, local);
    }
    Ok(())
}

/// All fixtures reachable from a set of tests, following every edge.
fn reachable_fixtures(graph: &Graph, tests: &[usize]) -> HashSet<usize> {
    let mut seen = HashSet::new();
    let mut stack: Vec<usize> = tests.to_vec();
    while let Some(node) = stack.pop() {
        for edge in &graph.nodes[node].edges {
            if seen.insert(edge.target) {
                stack.push(edge.target);
            }
        }
    }
    seen
}
