//! Run a crate's testrs suite by generating an ephemeral harness crate under
//! the target directory and executing it. The analyzed crate's worktree is
//! never modified — it doesn't even need kitest/tokio dev-dependencies.
//!
//! The harness is a `harness = false` test target so it's a real cargo test
//! target: `cargo test` runs it directly, and `cargo nextest` can discover,
//! list, and run it process-per-test.

use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::codegen;
use crate::discover::Discovery;
use crate::graph::Graph;

/// Generate the harness crate and run it, returning its process exit code.
/// With `nextest`, run it via `cargo nextest run`; otherwise `cargo test`.
pub fn run(discovery: &Discovery, graph: &Graph, nextest: bool) -> Result<i32> {
    let source = codegen::generate(discovery, graph)?;

    // Ephemeral harness crate: <target>/testrs/<crate>/. `target/` is gitignored,
    // so nothing leaks into the worktree.
    let crate_dir = discovery
        .target_dir
        .join("testrs")
        .join(&discovery.crate_name);
    std::fs::create_dir_all(crate_dir.join("src"))
        .with_context(|| format!("creating {}", crate_dir.display()))?;
    std::fs::create_dir_all(crate_dir.join("tests"))?;

    // The harness needs `testrs` (for `TestArgs` / `TestCaseName`).
    let Some(testrs_dir) = &discovery.testrs_manifest_dir else {
        bail!("the analyzed crate does not depend on `testrs`");
    };

    // A standalone `[workspace]` keeps the parent workspace from adopting this
    // crate; the analyzed crate is brought in as a path dependency. The harness
    // is a `harness = false` test target so nextest can drive it.
    let manifest = format!(
        "# @generated by testrs — do not edit.\n\
         [package]\n\
         name = \"testrs-harness-{name}\"\n\
         version = \"0.0.0\"\n\
         edition = \"2024\"\n\
         publish = false\n\
         \n\
         [workspace]\n\
         \n\
         [dependencies]\n\
         {package} = {{ path = {manifest_dir:?} }}\n\
         testrs = {{ path = {testrs_dir:?} }}\n\
         kitest = \"0.5\"\n\
         tokio = {{ version = \"1\", features = [\"rt-multi-thread\"] }}\n\
         \n\
         [[test]]\n\
         name = \"harness\"\n\
         path = \"tests/harness.rs\"\n\
         harness = false\n",
        name = discovery.crate_name,
        package = discovery.package_name,
        manifest_dir = discovery.manifest_dir,
    );
    std::fs::write(crate_dir.join("Cargo.toml"), manifest)?;
    // Empty lib so the package has a non-test target; the harness is the test.
    std::fs::write(crate_dir.join("src/lib.rs"), "// @generated by testrs.\n")?;
    std::fs::write(crate_dir.join("tests/harness.rs"), source)?;

    let manifest_path = crate_dir.join("Cargo.toml");
    let mut cmd = Command::new("cargo");
    if nextest {
        cmd.args(["nextest", "run", "--manifest-path"]).arg(&manifest_path);
    } else {
        cmd.args(["test", "--manifest-path"])
            .arg(&manifest_path)
            .args(["--test", "harness"]);
    }
    let status = cmd.status().context("running the generated harness")?;
    Ok(status.code().unwrap_or(1))
}
