//! Run a crate's testrs suite by generating an ephemeral harness crate under
//! the target directory and executing it. The analyzed crate's worktree is
//! never modified — it doesn't even need kitest/tokio dev-dependencies.
//!
//! The harness is a `harness = false` test target so it's a real cargo test
//! target: `cargo test` runs it directly, and `cargo nextest` can discover,
//! list, and run it process-per-test.

use std::fmt::Write as _;
use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::codegen;
use crate::discover::Discovery;
use crate::graph::Graph;

/// Generate the harness crate and run it, returning its process exit code.
/// With `nextest`, run it via `cargo nextest run`; otherwise `cargo test`.
// `{path:?}` deliberately emits a quoted, escaped string for TOML paths.
#[allow(clippy::unnecessary_debug_formatting)]
pub fn run(discovery: &Discovery, graph: &Graph, nextest: bool) -> Result<i32> {
    let source = codegen::generate(discovery, graph)?;

    // Ephemeral harness crate: <target>/testrs/<crate>/. `target/` is gitignored,
    // so nothing leaks into the worktree.
    let crate_dir = discovery
        .target_dir
        .join("testrs")
        .join(&discovery.crate_name);
    std::fs::create_dir_all(crate_dir.join("tests"))
        .with_context(|| format!("creating {}", crate_dir.display()))?;

    // The harness needs `testrs` (for `TestArgs` / `TestCaseName`).
    let Some(testrs_dir) = &discovery.testrs_manifest_dir else {
        bail!("the analyzed crate does not depend on `testrs`");
    };

    // Any external crate the harness names a type from (e.g. a shared fixture
    // returning `rusqlite::Connection`) must be a dependency too, pinned to the
    // same version the analyzed crate resolved.
    let mut extra_deps = String::new();
    for name in codegen::external_crates(discovery) {
        let Some(dep) = discovery.dependencies.get(&name) else {
            continue;
        };
        if matches!(dep.package.as_str(), "testrs" | "kitest")
            || dep.package == discovery.package_name
        {
            continue;
        }
        let _ = writeln!(extra_deps, "{} = \"={}\"", dep.package, dep.version);
    }

    // Name the harness package after the crate under test so nextest shows a
    // clean `<crate>::harness` binary id (cargo allows the same-named path dep,
    // and a test-only package needs no lib). A standalone `[workspace]` keeps
    // the parent workspace from adopting it.
    let manifest = format!(
        "# @generated by testrs — do not edit.\n\
         [package]\n\
         name = {package:?}\n\
         version = \"0.0.0\"\n\
         edition = \"2024\"\n\
         publish = false\n\
         \n\
         [workspace]\n\
         \n\
         [dependencies]\n\
         {package} = {{ path = {manifest_dir:?} }}\n\
         testrs = {{ path = {testrs_dir:?} }}\n\
         kitest = \"0.5\"\n\
         {extra_deps}\
         \n\
         [[test]]\n\
         name = \"harness\"\n\
         path = \"tests/harness.rs\"\n\
         harness = false\n",
        package = discovery.package_name,
        manifest_dir = discovery.manifest_dir,
    );
    std::fs::write(crate_dir.join("Cargo.toml"), manifest)?;
    std::fs::write(crate_dir.join("tests/harness.rs"), source)?;

    let manifest_path = crate_dir.join("Cargo.toml");
    let mut cmd = Command::new("cargo");
    if nextest {
        cmd.args(["nextest", "run", "--manifest-path"])
            .arg(&manifest_path);
    } else {
        cmd.args(["test", "--manifest-path"])
            .arg(&manifest_path)
            .args(["--test", "harness"]);
    }
    let status = cmd.status().context("running the generated harness")?;
    Ok(status.code().unwrap_or(1))
}
