//! Run a crate's testrs suite by generating an ephemeral harness crate under
//! the target directory and executing it. The analyzed crate's worktree is
//! never modified — it doesn't even need kitest/tokio dev-dependencies.

use std::process::Command;

use anyhow::{Context, Result};

use crate::codegen;
use crate::discover::{CaseNameStrategy, Discovery};
use crate::graph::Graph;

/// Generate the harness crate and run it, returning its process exit code.
pub fn run(discovery: &Discovery, graph: &Graph) -> Result<i32> {
    let source = codegen::generate(discovery, graph)?;

    // Ephemeral harness crate: <target>/testrs/<crate>/. `target/` is gitignored,
    // so nothing leaks into the worktree.
    let crate_dir = discovery
        .target_dir
        .join("testrs")
        .join(&discovery.crate_name);
    let src_dir = crate_dir.join("src");
    std::fs::create_dir_all(&src_dir).with_context(|| format!("creating {}", src_dir.display()))?;

    // `testrs` is only needed when a case uses the `TestCaseName` trait.
    let uses_testrs = discovery
        .items
        .iter()
        .any(|i| i.cases.iter().any(|c| c.name_strategy == CaseNameStrategy::TestCaseName));
    let testrs_dep = match (uses_testrs, &discovery.testrs_manifest_dir) {
        (true, Some(dir)) => format!("testrs = {{ path = {dir:?} }}\n"),
        _ => String::new(),
    };

    // A standalone `[workspace]` keeps the parent workspace from adopting this
    // crate; the analyzed crate is brought in as a path dependency.
    let manifest = format!(
        "# @generated by testrs — do not edit.\n\
         [package]\n\
         name = \"testrs-harness-{name}\"\n\
         version = \"0.0.0\"\n\
         edition = \"2024\"\n\
         publish = false\n\
         \n\
         [workspace]\n\
         \n\
         [dependencies]\n\
         {package} = {{ path = {manifest_dir:?} }}\n\
         kitest = \"0.5\"\n\
         tokio = {{ version = \"1\", features = [\"rt-multi-thread\"] }}\n\
         {testrs_dep}",
        name = discovery.crate_name,
        package = discovery.package_name,
        manifest_dir = discovery.manifest_dir,
    );
    std::fs::write(crate_dir.join("Cargo.toml"), manifest)?;
    std::fs::write(src_dir.join("main.rs"), source)?;

    let status = Command::new("cargo")
        .arg("run")
        .arg("--manifest-path")
        .arg(crate_dir.join("Cargo.toml"))
        .status()
        .context("running the generated harness")?;

    Ok(status.code().unwrap_or(1))
}
