//! Proc-macro markers for testrs.
//!
//! `#[fixture]` and `#[test]` attach an inert `#[diagnostic::testrs::*]` marker
//! to the annotated function and otherwise leave it unchanged. The `diagnostic`
//! namespace is the only attribute namespace rustdoc preserves verbatim in its
//! JSON output, so the testrs CLI can discover these markers — and their
//! arguments — from each item's `attrs`. No setup or wiring logic lives here;
//! that is generated by the CLI.
//!
//! Because the marker lives in the `diagnostic::testrs` namespace, which rustc
//! does not recognise, a crate using testrs must allow the corresponding lint
//! at its root:
//!
//! ```ignore
//! #![allow(unknown_or_malformed_diagnostic_attributes)]
//! ```

use proc_macro::TokenStream;
use proc_macro2::{Delimiter, Group, Ident, Span, TokenStream as TokenStream2, TokenTree};
use quote::quote;

/// Emit the annotated function, prefixed with a
/// `#[diagnostic::testrs::<kind>(<args>)]` marker carrying the macro's arguments.
///
/// The generated kitest harness lives in a separate crate, so it can only call
/// fixtures/tests through the crate's public path. We therefore promote a
/// plain (private) marked function to `pub`; functions with an explicit
/// visibility are left as written.
fn mark(kind: &str, attr: TokenStream, item: TokenStream) -> TokenStream {
    let kind = Ident::new(kind, Span::call_site());
    let args = TokenStream2::from(attr);
    let mut item = ensure_pub(TokenStream2::from(item));

    let marker = if args.is_empty() {
        quote! { #[diagnostic::testrs::#kind] }
    } else {
        quote! { #[diagnostic::testrs::#kind(#args)] }
    };

    // A `cases(param = provider)` binding lives only as tokens inside the inert
    // `diagnostic` attribute, where rust-analyzer can't resolve it. Re-emit each
    // side as a real reference at the start of the body, keeping its source spans,
    // so go-to-definition works: `param` resolves to the function parameter (in
    // scope there) and `provider` to its function. `&` avoids moving a non-Copy
    // param; `let _` binds nothing and discards.
    let bindings = cases_bindings(&args);
    if !bindings.is_empty() {
        let refs: TokenStream2 = bindings
            .iter()
            .map(|(param, provider)| quote! { let _ = &#param; let _ = &#provider; })
            .collect();
        item = inject_into_body(item, refs);
    }

    // The only caller of a fixture/test is the generated harness, which the
    // compiler can't see while checking this crate — so suppress dead-code for
    // the marked item (precisely, rather than crate-wide).
    quote! {
        #[allow(dead_code)]
        #marker
        #item
    }
    .into()
}

/// Extract the `(param, provider)` token-streams from a `cases(param = provider,
/// ...)` argument list — the tokens before and after each top-level `=`, with
/// their source spans preserved — so they can be re-emitted as resolvable
/// references.
fn cases_bindings(args: &TokenStream2) -> Vec<(TokenStream2, TokenStream2)> {
    // Find the `cases(...)` group.
    let mut iter = args.clone().into_iter().peekable();
    let mut inner = None;
    while let Some(tt) = iter.next() {
        if matches!(&tt, TokenTree::Ident(id) if *id == "cases")
            && let Some(TokenTree::Group(g)) = iter.peek()
            && g.delimiter() == Delimiter::Parenthesis
        {
            inner = Some(g.stream());
            break;
        }
    }
    let Some(inner) = inner else {
        return Vec::new();
    };

    // Each binding is `param = provider`, comma-separated.
    let mut bindings = Vec::new();
    let (mut lhs, mut rhs) = (TokenStream2::new(), TokenStream2::new());
    let mut after_eq = false;
    for tt in inner {
        let is_comma = matches!(&tt, TokenTree::Punct(p) if p.as_char() == ',');
        let is_eq = matches!(&tt, TokenTree::Punct(p) if p.as_char() == '=');
        if is_comma {
            if !lhs.is_empty() && !rhs.is_empty() {
                bindings.push((std::mem::take(&mut lhs), std::mem::take(&mut rhs)));
            }
            (lhs, rhs) = (TokenStream2::new(), TokenStream2::new());
            after_eq = false;
        } else if is_eq && !after_eq {
            after_eq = true;
        } else if after_eq {
            rhs.extend([tt]);
        } else {
            lhs.extend([tt]);
        }
    }
    if !lhs.is_empty() && !rhs.is_empty() {
        bindings.push((lhs, rhs));
    }
    bindings
}

/// Prepend statements to a function's body — the last top-level brace group of
/// the item's tokens. If there's no body (no brace group), the item is returned
/// unchanged.
fn inject_into_body(item: TokenStream2, stmts: TokenStream2) -> TokenStream2 {
    let mut tokens: Vec<TokenTree> = item.into_iter().collect();
    let body = tokens
        .iter()
        .rposition(|tt| matches!(tt, TokenTree::Group(g) if g.delimiter() == Delimiter::Brace));
    if let Some(i) = body
        && let TokenTree::Group(g) = &tokens[i]
    {
        let mut inner = stmts;
        inner.extend(g.stream());
        let mut new_body = Group::new(Delimiter::Brace, inner);
        new_body.set_span(g.span());
        tokens[i] = TokenTree::Group(new_body);
    }
    tokens.into_iter().collect()
}

/// Prepend `pub` to the item unless it already carries a visibility. Leading
/// outer attributes (`#[...]`) are skipped; the first remaining token decides —
/// if it's `pub` the item is left untouched, otherwise `pub` is inserted there.
fn ensure_pub(item: TokenStream2) -> TokenStream2 {
    let tokens: Vec<TokenTree> = item.into_iter().collect();

    let mut i = 0;
    while let Some(TokenTree::Punct(p)) = tokens.get(i) {
        if p.as_char() != '#' {
            break;
        }
        match tokens.get(i + 1) {
            Some(TokenTree::Group(g)) if g.delimiter() == Delimiter::Bracket => i += 2,
            _ => break,
        }
    }

    if matches!(tokens.get(i), Some(TokenTree::Ident(id)) if *id == "pub") {
        return tokens.into_iter().collect();
    }

    let mut out = TokenStream2::new();
    out.extend(tokens[..i].iter().cloned());
    out.extend([TokenTree::Ident(Ident::new("pub", Span::call_site()))]);
    out.extend(tokens[i..].iter().cloned());
    out
}

/// Marks a function as a testrs fixture.
#[proc_macro_attribute]
pub fn fixture(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("fixture", attr, item)
}

/// Marks a function as a testrs test.
#[proc_macro_attribute]
pub fn test(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("test", attr, item)
}

/// Marks the function testrs uses to run async fixtures/tests to completion —
/// the bridge to your async runtime. It must be callable as
/// `fn(impl Future<Output = T>) -> T` (typically `fn rt<F: Future>(f: F) -> F::Output`).
/// At most one per crate; without one, testrs falls back to `testrs::block_on`.
#[proc_macro_attribute]
pub fn runtime(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("runtime", attr, item)
}

/// Marks a function as the teardown for the fixture it takes by value. testrs runs
/// it — synchronous or `async` (driven through the [`runtime`] bridge) — when that
/// fixture's scope ends, instead of dropping the value. It must take exactly one
/// parameter, the fixture, by value:
///
/// ```ignore
/// #[testrs::tear_down]
/// async fn close(db: Database) { db.pool.close().await; }
/// ```
#[proc_macro_attribute]
pub fn tear_down(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("tear_down", attr, item)
}
