//! Proc-macro markers for testrs.
//!
//! `#[fixture]` and `#[test]` attach an inert `#[diagnostic::testrs::*]` marker
//! to the annotated function and otherwise leave it unchanged. The `diagnostic`
//! namespace is the only attribute namespace rustdoc preserves verbatim in its
//! JSON output, so the testrs CLI can discover these markers — and their
//! arguments — from each item's `attrs`. No setup or wiring logic lives here;
//! that is generated by the CLI.
//!
//! Because the marker lives in the `diagnostic::testrs` namespace, which rustc
//! does not recognise, a crate using testrs must allow the corresponding lint
//! at its root:
//!
//! ```ignore
//! #![allow(unknown_or_malformed_diagnostic_attributes)]
//! ```

use proc_macro::TokenStream;
use proc_macro2::{Delimiter, Ident, Span, TokenStream as TokenStream2, TokenTree};
use quote::quote;

/// Emit the annotated function, prefixed with a
/// `#[diagnostic::testrs::<kind>(<args>)]` marker carrying the macro's arguments.
///
/// The generated kitest harness lives in a separate crate, so it can only call
/// fixtures/tests through the crate's public path. We therefore promote a
/// plain (private) marked function to `pub`; functions with an explicit
/// visibility are left as written.
fn mark(kind: &str, attr: TokenStream, item: TokenStream) -> TokenStream {
    let kind = Ident::new(kind, Span::call_site());
    let args = TokenStream2::from(attr);
    let item = ensure_pub(TokenStream2::from(item));

    let marker = if args.is_empty() {
        quote! { #[diagnostic::testrs::#kind] }
    } else {
        quote! { #[diagnostic::testrs::#kind(#args)] }
    };

    // The only caller of a fixture/test is the generated harness, which the
    // compiler can't see while checking this crate — so suppress dead-code for
    // the marked item (precisely, rather than crate-wide).
    quote! {
        #[allow(dead_code)]
        #marker
        #item
    }
    .into()
}

/// Prepend `pub` to the item unless it already carries a visibility. Leading
/// outer attributes (`#[...]`) are skipped; the first remaining token decides —
/// if it's `pub` the item is left untouched, otherwise `pub` is inserted there.
fn ensure_pub(item: TokenStream2) -> TokenStream2 {
    let tokens: Vec<TokenTree> = item.into_iter().collect();

    let mut i = 0;
    while let Some(TokenTree::Punct(p)) = tokens.get(i) {
        if p.as_char() != '#' {
            break;
        }
        match tokens.get(i + 1) {
            Some(TokenTree::Group(g)) if g.delimiter() == Delimiter::Bracket => i += 2,
            _ => break,
        }
    }

    if matches!(tokens.get(i), Some(TokenTree::Ident(id)) if *id == "pub") {
        return tokens.into_iter().collect();
    }

    let mut out = TokenStream2::new();
    out.extend(tokens[..i].iter().cloned());
    out.extend([TokenTree::Ident(Ident::new("pub", Span::call_site()))]);
    out.extend(tokens[i..].iter().cloned());
    out
}

/// Marks a function as a testrs fixture.
#[proc_macro_attribute]
pub fn fixture(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("fixture", attr, item)
}

/// Marks a function as a testrs test.
#[proc_macro_attribute]
pub fn test(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("test", attr, item)
}

/// Marks the function testrs uses to run async fixtures/tests to completion —
/// the bridge to your async runtime. It must be callable as
/// `fn(impl Future<Output = T>) -> T` (typically `fn rt<F: Future>(f: F) -> F::Output`).
/// At most one per crate; without one, testrs falls back to `testrs::block_on`.
#[proc_macro_attribute]
pub fn runtime(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("runtime", attr, item)
}

/// Marks a function as the teardown for the fixture it takes by value. testrs runs
/// it — synchronous or `async` (driven through the [`runtime`] bridge) — when that
/// fixture's scope ends, instead of dropping the value. It must take exactly one
/// parameter, the fixture, by value:
///
/// ```ignore
/// #[testrs::tear_down]
/// async fn close(db: Database) { db.pool.close().await; }
/// ```
#[proc_macro_attribute]
pub fn tear_down(attr: TokenStream, item: TokenStream) -> TokenStream {
    mark("tear_down", attr, item)
}
