//! Proc-macro markers for testrs.
//!
//! `#[fixture]` and `#[test]` are intentionally thin: they emit the annotated
//! function unchanged plus discoverable metadata for the `testrs` CLI. No setup
//! or wiring logic lives here — that is generated by the CLI.
//!
//! These are currently identity passthroughs; metadata emission is added next.

use proc_macro::TokenStream;

/// Marks a function as a testrs fixture.
#[proc_macro_attribute]
pub fn fixture(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Marks a function as a testrs test.
#[proc_macro_attribute]
pub fn test(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}
