// @generated by testrs — do not edit.
#![allow(unknown_or_malformed_diagnostic_attributes)]

use std::cell::RefCell;
use std::ops::ControlFlow;
use std::process::Termination;

use kitest::group::{TestGroupOutcomes, TestGroupRunner};
use kitest::prelude::*;
use kitest::runner::SimpleRunner;
use tokio::runtime::Handle;

#[derive(Default)]
struct UsersFixtures {
    config: Option<testrs_example::Config>,
    database: Option<testrs_example::Database>,
}
thread_local! {
    static USERS: RefCell<UsersFixtures> = RefCell::new(UsersFixtures::default());
}

struct FixtureRunner { handle: Handle }

impl<'t> TestGroupRunner<'t, &'static str, &'static str, ()> for FixtureRunner {
    fn run_group<F>(&self, f: F, key: &&'static str, _ctx: Option<&()>)
        -> ControlFlow<TestGroupOutcomes<'t>, TestGroupOutcomes<'t>>
    where F: FnOnce() -> TestGroupOutcomes<'t> {
        match *key {
            "users" => {
                let config = testrs_example::config();
                let database = self.handle.block_on(testrs_example::database(&config));
                USERS.with(|c| {
                    let mut c = c.borrow_mut();
                    c.config = Some(config);
                    c.database = Some(database);
                });
                let outcomes = f();
                USERS.with(|c| *c.borrow_mut() = UsersFixtures::default());
                ControlFlow::Continue(outcomes)
            }
            _ => ControlFlow::Continue(f()),
        }
    }
}

fn tests(handle: Handle) -> Vec<Test<&'static str>> {
    vec![
        Test::new(
            TestFnHandle::from_boxed({
                let handle = handle.clone();
                move || {
                    USERS.with(|c| {
                        let c = c.borrow();
                        let user = testrs_example::users::user(c.database.as_ref().unwrap());
                        handle.block_on(testrs_example::users::test_find_user(c.database.as_ref().unwrap(), user));
                    });
                }
            }),
            TestMeta { name: "test_find_user".into(), extra: "users", ..Default::default() },
        ),
    ]
}

fn main() -> impl Termination {
    let rt = tokio::runtime::Runtime::new().unwrap();
    let handle = rt.handle().clone();
    let tests = tests(handle.clone());
    kitest::harness(&tests)
        .with_grouper(|m: &TestMeta<&'static str>| m.extra)
        .with_group_runner(FixtureRunner { handle })
        .with_runner(SimpleRunner::default())
        .run()
        .report()
}
